IDSFFile: "SFs/UL2018_mu_ID.json"
kinematics: 
    Muon:
        lohi:
            pt:
                low: 27
                high: 2000
            eta:
                low: -2.4
                high: 2.4
        value: 
            tightId: 1
correctionLib:
    weightName: "NUM_TightID_DEN_TrackerMuons"
    eraName: "2018_UL"
branchNames:
    sf: "MuonIDWeight"
    sfup: "MuonIDWeightUp"
    sfdown: "MuonIDWeightDown"
        