tag: "earlyJan"
DatasetJSONFolder: "Datasets"
outputDirBase: "/mnt/disk1/skimmed_Run2/"

processFlow:
    selection:
      UL2016preVFP:
        inputStage: "skimmed"
        inputTag : "nfs"
      UL2016postVFP:
        inputStage: "skimmed"
        inputTag : "nfs"
      UL2017:
        inputStage: "skimmed"
        inputTag : "nfs"
      UL2018:
        inputStage: "skimmed"
        inputTag : "nfs"
    reco:
      UL2016preVFP:
        inputStage: "selection"
        inputTag : "earlyJan"
      UL2016postVFP:
        inputStage: "selection"
        inputTag : "earlyJan"
      UL2017:
        inputStage: "selection"
        inputTag : "earlyJan"
      UL2018:
        inputStage: "selection"
        inputTag : "earlyJan"
    observables:
      UL2016preVFP:
        inputStage: "reco"
        inputTag : "earlyJan"
      UL2016postVFP:
        inputStage: "reco"
        inputTag : "earlyJan"
      UL2017:
        inputStage: "reco"
        inputTag : "earlyJan"
      UL2018:
        inputStage: "reco"
        inputTag : "earlyJan"
    BDTvariables:
      UL2016preVFP:
        inputStage: "observables"
        inputTag : "earlyJan"
      UL2016postVFP:
        inputStage: "observables"
        inputTag : "earlyJan"
      UL2017:
        inputStage: "observables"
        inputTag : "earlyJan"
      UL2018:
        inputStage: "observables"
        inputTag : "earlyJan"
    BDTScore:
      UL2016preVFP:
        inputStage: "BDTvariables"
        inputTag : "earlyJan"
      UL2016postVFP:
        inputStage: "BDTvariables"
        inputTag : "earlyJan"
      UL2017:
        inputStage: "BDTvariables"
        inputTag : "earlyJan"
      UL2018:
        inputStage: "BDTvariables"
        inputTag : "earlyJan"
