tag: "lateOctober"
DatasetJSONFolder: "/home/mukund/Projects/SkimandSlim/NanoAODTools/Datasets"
outputDirBase: "/mnt/disk1/skimmed_Run2/"

processFlow:
    selection:
      UL2016preVFP:
        inputStage: "skimmed"
        inputTag : "nfs"
      UL2016postVFP:
        inputStage: "skimmed"
        inputTag : "nfs"
      UL2017:
        inputStage: "skimmed"
        inputTag : "nfs"
      UL2018:
        inputStage: "skimmed"
        inputTag : "nfs"
    reco:
      UL2016preVFP:
        inputStage: "selection"
        inputTag : "lateOctober"
      UL2016postVFP:
        inputStage: "selection"
        inputTag : "lateOctober"
      UL2017:
        inputStage: "selection"
        inputTag : "lateOctober"
      UL2018:
        inputStage: "selection"
        inputTag : "lateOctober"
    observables:
      UL2016preVFP:
        inputStage: "reco"
        inputTag : "lateOctober"
      UL2016postVFP:
        inputStage: "reco"
        inputTag : "lateOctober"
      UL2017:
        inputStage: "reco"
        inputTag : "lateOctober"
      UL2018:
        inputStage: "reco"
        inputTag : "lateOctober"
    BDTvariables:
      UL2016preVFP:
        inputStage: "observables"
        inputTag : "lateOctober"
      UL2016postVFP:
        inputStage: "observables"
        inputTag : "lateOctober"
      UL2017:
        inputStage: "observables"
        inputTag : "lateOctober"
      UL2018:
        inputStage: "observables"
        inputTag : "lateOctober"
    BDTScore:
      UL2016preVFP:
        inputStage: "BDTvariables"
        inputTag : "lateOctober"
      UL2016postVFP:
        inputStage: "BDTvariables"
        inputTag : "lateOctober"
      UL2017:
        inputStage: "BDTvariables"
        inputTag : "lateOctober"
      UL2018:
        inputStage: "BDTvariables"
        inputTag : "lateOctober"
