tag : 'midNov'
DatasetJSONFolder:
  ehep154.ehep.tifr.res.in: 'Datasets'
  localhost.localdomain: 'Datasets'
DatasetJSONFolder : 
  ehep154.ehep.tifr.res.in: 'Datasets'
  localhost.localdomain: 'Datasets'
outputDirBase : 
  ehep154.ehep.tifr.res.in: '/mnt/disk1/skimmed_Run2/'
  localhost.localdomain: '/home/mukund/outputs'
efficiencyFolder : 
  ehep154.ehep.tifr.res.in: 'SFs/Efficiency'
  localhost.localdomain: 'SFs/Efficiency'

eras:
  - UL2016preVFP
  - UL2016postVFP
  - UL2017
  - UL2018

stages:
  - skimmed
  - selection
  - reco
  - observables
  - BDTvariables
  - BDTScore

gJSONs:
  UL2016preVFP:
    ehep154.ehep.tifr.res.in: "goldenJSONs/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.json"
    localhost.localdomain: "goldenJSONs/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.json"
  UL2016postVFP:
    ehep154.ehep.tifr.res.in: "goldenJSONs/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.json"
    localhost.localdomain: "goldenJSONs/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.json"
  UL2017:
    ehep154.ehep.tifr.res.in: "goldenJSONs/Cert_294927-306462_13TeV_UL2017_Collisions17_GoldenJSON.json"
    localhost.localdomain: "goldenJSONs/Cert_294927-306462_13TeV_UL2017_Collisions17_GoldenJSON.json"
  UL2018:
    ehep154.ehep.tifr.res.in: "goldenJSONs/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.json"
    localhost.localdomain: "goldenJSONs/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.json"

branchFile: "python/postprocessing/examples/keep_and_drop.txt"

btag_threshold:
  UL2016preVFP: 0.2598
  UL2016postVFP: 0.2489
  UL2017: 0.3040
  UL2018: 0.2783

hltFlag:
  UL2016preVFP: "(HLT_IsoMu24 || HLT_IsoTkMu24)"
  UL2016postVFP: "(HLT_IsoMu24 || HLT_IsoTkMu24)"
  UL2017: "HLT_IsoMu27"
  UL2018: "HLT_IsoMu24"

cuts:
  atleast_n_muons: 
    UL2016preVFP: 1
    UL2016postVFP: 1
    UL2017: 1
    UL2018: 1
  atleast_n_btagged_jets:
    UL2016preVFP: 2
    UL2016postVFP: 2
    UL2017: 2
    UL2018: 2
  atleast_n_jets:
    UL2016preVFP: 4
    UL2016postVFP: 4
    UL2017: 4
    UL2018: 4

muon:
  pt:
    lo:
      UL2016preVFP: 26
      UL2016postVFP: 26
      UL2017: 29
      UL2018: 27
    hi:
      UL2016preVFP: 2000
      UL2016postVFP: 2000
      UL2017: 2000
      UL2018: 2000
  abs_eta:
    hi: 
      UL2016preVFP: 2.4
      UL2016postVFP: 2.4
      UL2017: 2.4
      UL2018: 2.4
  eta:
    lo:
      UL2016preVFP: -2.4
      UL2016postVFP: -2.4
      UL2017: -2.4
      UL2018: -2.4
    hi:
      UL2016preVFP: 2.4
      UL2016postVFP: 2.4
      UL2017: 2.4
      UL2018: 2.4
  iso:
    hi:
      UL2016preVFP: 0.06
      UL2016postVFP: 0.06
      UL2017: 0.06
      UL2018: 0.06
    lo:
      UL2016preVFP: -1.0
      UL2016postVFP: -1.0
      UL2017: -1.0
      UL2018: -1.0

jet:
  pt:
    lo:
      UL2016preVFP: 25
      UL2016postVFP: 25
      UL2017: 25
      UL2018: 25
  abs_eta:
    hi:
      UL2016preVFP: 2.4
      UL2016postVFP: 2.4
      UL2017: 2.4
      UL2018: 2.4

modules:
  MC:
    selection:
      - lheWeightSign
      - muonID
      - muonHLT
      - bTagging
    reco:
      - Reco
    observables:
      - Observables
      - yCalculator
    BDTvariables:
      - BDTVariable
    BDTScore:
      - applyBDT
  Data:
    selection: null
    reco:
      - Reco
    observables:
      - Observables
    BDTvariables:
      - BDTVariable
    BDTScore:
      - applyBDT


IDSFParams:
  IDSFFile:
    UL2016preVFP:
      ehep154.ehep.tifr.res.in: "SFs/UL2016preVFP_mu_ID.json"
      localhost.localdomain: "SFs/UL2016preVFP_mu_ID.json"
    UL2016postVFP:
      ehep154.ehep.tifr.res.in: "SFs/UL2016postVFP_mu_ID.json"
      localhost.localdomain: "SFs/UL2016postVFP_mu_ID.json"
    UL2017:
      ehep154.ehep.tifr.res.in: "SFs/UL2017_mu_ID.json"
      localhost.localdomain: "SFs/UL2017_mu_ID.json"
    UL2018:
      ehep154.ehep.tifr.res.in: "SFs/UL2018_mu_ID.json"
      localhost.localdomain: "SFs/UL2018_mu_ID.json"
  weightName: "NUM_TightID_DEN_TrackerMuons"
  eraName:
    UL2016preVFP: "2016preVFP_UL"
    UL2016postVFP: "2016postVFP_UL"
    UL2017: "2017_UL"
    UL2018: "2018_UL"
  nominalBranch: "MuonIDWeight"
  upBranch: "MuonIDWeightUp"
  downBranch: "MuonIDWeightDown"

HLTSFParams:
  HLTSFFile:
    UL2016preVFP:
      ehep154.ehep.tifr.res.in: "SFs/UL2016preVFP_mu_HLT.json"
      localhost.localdomain: "SFs/UL2016preVFP_mu_HLT.json"
    UL2016postVFP:
      ehep154.ehep.tifr.res.in: "SFs/UL2016postVFP_mu_HLT.json"
      localhost.localdomain: "SFs/UL2016postVFP_mu_HLT.json"
    UL2017:
      ehep154.ehep.tifr.res.in: "SFs/UL2017_mu_HLT.json"
      localhost.localdomain: "SFs/UL2017_mu_HLT.json"
    UL2018:
      ehep154.ehep.tifr.res.in: "SFs/UL2018_mu_HLT.json"
      localhost.localdomain: "SFs/UL2018_mu_HLT.json"
  weightName: 
    UL2016preVFP: "NUM_IsoMu24_or_IsoTkMu24_DEN_CutBasedIdTight_and_PFIsoTight"
    UL2016postVFP: "NUM_IsoMu24_or_IsoTkMu24_DEN_CutBasedIdTight_and_PFIsoTight"
    UL2017: "NUM_IsoMu27_DEN_CutBasedIdTight_and_PFIsoTight"
    UL2018: "NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight"
  nominalBranch: "MuonHLTWeight"
  statBranch: "MuonHLTWeightStat"
  systBranch: "MuonHLTWeightSyst"

lheWeightSignParams:
  nominalBranch: "LHEWeightSign"

bTagSFParams:
  bTagSFFile: 
    UL2016preVFP:
      ehep154.ehep.tifr.res.in: "SFs/UL2016preVFP_jet_Btagging.json"
      localhost.localdomain: "SFs/UL2016preVFP_jet_Btagging.json"
    UL2016postVFP:
      ehep154.ehep.tifr.res.in: "SFs/UL2016postVFP_jet_Btagging.json"
      localhost.localdomain: "SFs/UL2016postVFP_jet_Btagging.json"
    UL2017:
      ehep154.ehep.tifr.res.in: "SFs/UL2017_jet_Btagging.json"
      localhost.localdomain: "SFs/UL2017_jet_Btagging.json"
    UL2018:
      ehep154.ehep.tifr.res.in: "SFs/UL2018_jet_Btagging.json"
      localhost.localdomain: "SFs/UL2018_jet_Btagging.json"
  nominalBranch: "bTaggingWeight"
  upBranch: "bTaggingWeightUp"
  downBranch: "bTaggingWeightDown"