bTagSFFile: "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/SFs/UL2016postVFP_jet_Btagging.json"
efficiencyFolder : "/home/mukund/Projects/updatedCoffea/Coffea_Analysis/src/SFs/Efficiency"
era : "UL2016postVFP"
bTagThreshold : 0.2489
branchNames:
    sf: "bTaggingWeight"
    sfup: "bTaggingWeightUp"
    sfdown: "bTaggingWeightDown"
        