gJSON: ""
branchsel: "python/postprocessing/examples/keep_and_drop.txt"
cuts:
    - "Sum$(Muon_pt > 26 && abs(Muon_eta) < 2.4 && Muon_tightId && Muon_pfRelIso04_all <= 0.06) >= 1"
    - "Sum$(Jet_pt > 25 && abs(Jet_eta) < 2.4 && Jet_btagDeepFlavB > 0.2489 && Jet_jetId == 6 && (Jet_pt > 50 | Jet_puId > 0)) >= 2"
    - "Sum$(Jet_pt > 25 && abs(Jet_eta) < 2.4 && Jet_jetId == 6 && (Jet_pt > 50 | Jet_puId > 0)) >= 4"
    - "(HLT_IsoMu24 || HLT_IsoTkMu24)"
    - "Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_eeBadScFilter"
modules:
    Data: null
    MC:
    - lheWeightSign
    - muonID
    - muonHLT
    - bTagging
    - jetPUID
