gJSON: "goldenJSONs/Cert_294927-306462_13TeV_UL2017_Collisions17_GoldenJSON.json"
branchsel: "python/postprocessing/examples/keep_and_drop.txt"
cuts:
    - "Sum$(Muon_pt > 29 && abs(Muon_eta) < 2.4 && Muon_tightId && Muon_pfRelIso04_all <= 0.06) >= 1"
    - "Sum$(Jet_pt > 25 && abs(Jet_eta) < 2.4 && Jet_btagDeepFlavB > 0.304 && Jet_jetId == 6 && (Jet_pt > 50 | Jet_puId > 0)) >= 2"
    - "Sum$(Jet_pt > 25 && abs(Jet_eta) < 2.4 && Jet_jetId == 6 && (Jet_pt > 50 | Jet_puId > 0)) >= 4"
    - "HLT_IsoMu27"
    - "Flag_goodVertices && Flag_globalSuperTightHalo2016Filter && Flag_HBHENoiseFilter && Flag_HBHENoiseIsoFilter && Flag_EcalDeadCellTriggerPrimitiveFilter && Flag_BadPFMuonFilter && Flag_BadPFMuonDzFilter && Flag_eeBadScFilter"
modules:
    Data: null
    MC:
    - lheWeightSign
    - muonID
    - muonHLT
    - bTagging
